env=dev
app.id=flink-platform-web
apollo.meta=https://config-dev.tigerfintech.com/dev-meta
apollo.cluster=default
apollo.cache-dir=./config-cache
# apollo.bootstrap.enabled=true
# apollo.bootstrap.namespaces=application
apollo.salt=shik-test
