server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 9104

spring:
  profiles:
    active: prod
  # redis
  redis:
    password: p2tUB7z2TOX+n0e8
    sentinel:
      master: mymaster
      nodes: 10.8.12.17:26379,10.8.12.18:26379,10.8.12.19:26379
      password: p2tUB7z2TOX+n0e8
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        max-wait: -1ms
        min-idle: 5
  # 多数据源
  datasource:
    dynamic:
      # strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master_platform: # platform
          url: jdbc:mysql://10.8.10.1:3306/platform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: signature
          password: JDdDzUqHQKk=
          driver-class-name: com.mysql.jdbc.Driver
        signature: # signature库
          url: jdbc:mysql://10.8.10.1:3306/data_signature?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: signature
          password: JDdDzUqHQKk=
          driver-class-name: com.mysql.jdbc.Driver
        hive:
          url: jdbc:hive2://10.8.12.11:10000/signature
          username: signature
          password: JDdDzUqHQKk=
          driver-class-name: org.apache.hive.jdbc.HiveDriver
  quartz:
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    jdbc:
      initialize-schema: never
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

flink:
  local:
    sql-dir: sql_file
    jar-dir: job_jar
  sql112:
    command: /data0/app/flink-1.12.0/bin/flink
    jar-file: hdfs:///flink/jars/job_jar/persona-platform-flink.jar
    class-name: com.itiger.persona.flink.Sql112Application
    yarn-provided-lib-dirs: hdfs:///flink/jars/flink_1.12.0/lib/

hadoop:
  user: admin
  password:
  hdfs-site: hdfs-site.xml
  core-site: core-site.xml
  local:
    data-dir: data_dir