name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Linux:
    strategy:
      matrix:
        java-version: [ 21 ]
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: './mvnw -Dskip.frontend=true clean verify'
