spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  config:
    import: classpath:storage-${spring.profiles.active}.yml

management:
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true
  endpoint:
    env:
      show-values: never
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
